version: '3.8'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - media_volume:/home/app/web/project/media
      # - /home/team18/seulkok/backend/services/nginx/nginx.conf:/etc/nginx/conf.d
      # - /home/team18/seulkok/backend/services/nginx/conf:/etc/nginx/ssl
      # - /home/team18/seulkok/backend/services/nginx/conf:/var/www/certbot
    ports:
      - 80:80
        # - 443:443
    depends_on:
      - web
  # certbot:
  #   image: certbot/certbot:latest
  #   command:certonly --webroot --webroot-path=/var/www/certbot --email myemail@google.com --agree-tos --no-eff-email -d domain.com
  #   volumes:
  #     - /home/team18/seulkok/backend/services/nginx/conf:
  #     - /home/team18/seulkok/backend/services/nginx/logs:
  #     - /home/team18/seulkok/backend/services/nginx/data:


volumes:
  postgres_data_prod:
  static_volume:
  media_volume:
